###
POST http://localhost/api/user
Content-Type: application/json

{
    "username": "keyra",
    "email": "keyra.almira@gmail.com",
    "password": "password"
}


###
POST http://localhost/api/user
Content-Type: application/json

{
    "username": "cuwah",
    "email": "cuwah.azkia@gmail.com",
    "password": "cuwah"
}


###
GET http://localhost/api/user
Content-Type: application/json