version: "3.9"

services:
  flask:
    # container_name: flask_manual
    image: flask_manual:0.0.1
    build:
      context: .
    ports:
      - ":5000"
    env_file: .env
    environment:
    - DB_URL=${DB_URL_DOCKER}
    - FLASK_PORT=${FLASK_PORT}
    depends_on:
      - flask_db
  
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - flask

  
  flask_db:
    container_name: flask_db
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file: .env
    environment:
      - POSTGRES_USER=${USER}
      - POSTGRES_PASSWORD=${PASSWORD}
      - POSTGRES_DB=${DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
  
volumes:
  pgdata: